# 1: SHORT LONG SHORT #

# 2: WHAT CENTURY IS THAT? #

# 3: LEAP YEARS (PART 1) #

# 4: LEAP YEARS (PART 2) #

# 5: MULTIPLES OF 3 AND 5 #

# 6: RUNNING TOTALS #

# 7: CONVERT A STRING TO A NUMBER! #

# 8: COVERT A STRING TO A SIGNED NUMBER! #

# 9: CONVERT A NUMBER TO A STRING! #

# 10: CONVERT A SIGNED NUMBR TO A STRING #
