# 1 ASCII STRING VALUE #

# 2 AFTER MIDNIHGT (PART 1) #

# 3 AFTER MIDNIGHT (PART 2) #

# 4 LETTER SWAP #

# 5 CLEAN UP THE WORDS #

# 6 LETTER COUNTER (PART 1) #

# 7 LETTER COUNTER (PART 2) #

# 8 ALPHABETICAL NUMBERS #

# 9  DDAAIILLYY DDOOUBBLLEE #

# 10 BANNERIZER #

# 11 SPIN ME AROUND IN CIRCLES #