#### LAUNCH SCHOOL SMALL PROBLEMS RB101-RB109 ####

# 1 SEARCHING 101 #

# 2 ARITHMETIC INTEGER #

# 3 COUNTING THE NUMBER OF CHARACTERS #

# 4 MULTIPLYING TWO NUMBERS #

# 5 SQUARING AN ARGUMENT #

# 6 EXCLUSIVE OR #

# 7 ODD LISTS #

# 8 PALINDROMIC STRINGS (PART 1) #

# 9 PALINDROMIC STRINGS (PART 2) #

# 10 PALINDROMIC NUMBERS #
